package de.luca.uebungsaufgaben.uebungsblatt08;

import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

class Recipes {

    public static final List<List<String>> recipes = new ArrayList<>();

    static {
        init();
    }

    private static void init() {
        recipes.add(Arrays.asList("\"125er\" Waffeln", "Mehl", "Butter", "Zucker", "Milch", "Ei(er)", "Salz"));
        recipes.add(Arrays.asList("\"A bis Z\"-Salat", "Zucchini", "Apfel", "Zwiebel(n)", "Salz", "Zucker", "Schmand", "Salz und Pfeffer", "Dill", "Rosinen", "Kräuter"));
        recipes.add(Arrays.asList("\"A whole lot of\" - Käse-Auflauf", "Käse", "Feta-Käse", "Mais", "Zwiebel(n)", "Hackfleisch", "Sauce Hollandaise", "Ingwer", "Salz und Pfeffer", "Rosmarin", "Thymian"));
        recipes.add(Arrays.asList("\"All-In-One\" gefüllte Paprikaschoten mit Tomatenreis", "Zwiebel(n)", "Rinderhackfleisch", "Paniermehl", "Ei(er)", "Paprikapulver", "Senf", "Tomatenmark", "Salz", "Pfeffer", "Paprikaschote(n)", "Zwiebel(n)", "Tomate(n)", "Sahne", "Milch", "Wasser", "Ajvar", "Reis", "Gemüsebrühe"));
        recipes.add(Arrays.asList("\"Alte Schnitzel\" - ein Auflauf mit Schnitzeln, Schinken und Champignons", "Schweineschnitzel", "Ei(er)", "Mehl", "Paniermehl", "Salz und Pfeffer", "Schlagsahne", "Schinken", "Zwiebel(n)", "Champignons", "Gouda"));
        recipes.add(Arrays.asList("\"Angry Bird\" Marmorkuchen", "Butter", "Zucker", "Ei(er)", "Mehl", "Milch", "Backpulver", "Salz"));
        recipes.add(Arrays.asList("\"Athen Toast\" - Hackfleisch-Schafskäse-Sandwich", "Hackfleisch", "Sandwichtoast", "Feta-Käse", "Paprikapulver", "Knoblauchpulver", "Salz und Pfeffer", "Tzatziki"));
        recipes.add(Arrays.asList("\"Auf die schnelle\" Chickenburger", "Burgerbrötchen", "Sauce", "Chicken Nuggets", "Käse", "Eisbergsalat"));
        recipes.add(Arrays.asList("\"Aufgehende Sonne\"", "Nudeln", "Geflügelfleisch", "Ananas", "Orange(n)", "Cocktailtomaten", "Kokosmilch", "Sherry", "Öl", "Kurkuma", "Chiliflocken", "Muskat", "Korianderpulver", "Cayennepfeffer", "Safranpulver", "Zucker", "Salz"));
        recipes.add(Arrays.asList("\"Ausgescheppte Knepp\"", "Kartoffeln, mehligkochend", "Salz", "Wasser", "Mehl", "Semmelbrösel", "Butter"));
        recipes.add(Arrays.asList("\"Autofahrer\"-Mojito", "Minze", "Limette(n)", "Limettensirup", "Zitronenlimonade", "Mineralwasser mit Kohlensäure", "Eiswürfel"));
        recipes.add(Arrays.asList("\"Barbara\"", "Weizen", "Wasser", "Zucker", "Mehl", "Rosinen", "Sesam", "Walnüsse", "Mandel(n)", "Zimt"));
        recipes.add(Arrays.asList("\"Beblätterter\" Hotdog", "Blätterteig", "Gurkensalat", "Zwiebel(n)", "Jalapeño", "Dijonsenf", "Wiener Würstchen", "Gouda", "Eigelb", "Kräuter der Provence", "Röstzwiebeln"));
        recipes.add(Arrays.asList("\"Beschwipste Prinzessin\" - weiße Sachertorte mit Erdbeerfüllung", "Butter", "Puderzucker", "Vanillezucker", "Kuvertüre", "Ei(er)", "Mehl", "Backpulver", "Salz", "Weinbrand", "Konfitüre", "Fondant"));
        recipes.add(Arrays.asList("\"Beschwipste\" Schoko-Cupcakes", "Schokolade", "Butter", "Zucker", "Vanillezucker", "Salz", "Ei(er)", "Mehl", "Backpulver", "Kirschwasser"));
        recipes.add(Arrays.asList("\"Betrunkener Franzose\"", "Ei(er)", "Salz", "Zucker", "Mehl", "Kakaopulver, ungesüßt", "Backpulver", "Sahne", "Schokolade", "Schokolade", "Waldfruchtmarmelade", "Rum", "Amarenakirsche(n)"));
        recipes.add(Arrays.asList("\"Big Ranch\" Maisbrot", "Maismehl", "Weizenmehl", "Backpulver", "Salz", "Butter", "Ei(er)", "Milch"));
        recipes.add(Arrays.asList("\"Black and White\" New York Cheesecake", "Bitterschokolade", "Schlagsahne"));
        recipes.add(Arrays.asList("\"Bleib gesund\"-Smoothie SuperNova", "Karotte(n)", "Apfel", "Ingwerwurzel", "Orange(n)", "Zitrone(n)"));
        recipes.add(Arrays.asList("\"Bloody Berry\" Halloween Smoothie", "Beeren", "Naturjoghurt", "Milch", "Honig", "Süßigkeiten"));
        recipes.add(Arrays.asList("\"Bohnetten\" - vegane Frikadellen/Bouletten", "Kidneybohnen", "Haferflocken", "Wasser", "Flohsamenschalen", "Zwiebel(n), rot", "Knoblauch", "Gewürzpaste", "Gewürz(e)", "Thymian", "Senf"));
        recipes.add(Arrays.asList("\"Bottermelk Anballerste\"", "Kartoffel(n)", "Zwiebel(n)", "Butter", "Mehl", "Buttermilch", "Salz", "Pfeffer", "Muskatnuss", "Blutwurst"));
        recipes.add(Arrays.asList("\"Bounty\" low carb", "Quark", "Kokosraspel", "Erythrit (Zuckerersatz)", "Schokoladendrops"));
        recipes.add(Arrays.asList("\"Brotschnitzel\"", "Brot(e)", "Ei(er)", "Öl", "Gewürz(e)"));
        recipes.add(Arrays.asList("\"Bulit\" polnischer Kartoffel-Speck-Eintopf", "Kartoffel(n)", "Lorbeerblätter", "Pimentkörner", "Pfefferkörner", "Speckwürfel", "Zwiebel(n)", "Buttermilch", "Sauerrahm", "Dill", "Schnittlauch", "Essig", "Ei(er)", "Matjesfilet(s)", "Mehl", "Salz und Pfeffer", "Zucker"));
        recipes.add(Arrays.asList("\"Butter bei die Scampi\"", "Scampi", "Knoblauch", "Butter", "Cointreau", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Cakranegara\" - Mangokuchen mit Mandeln und Rosinen", "Wasser, lauwarm", "Trockenhefe", "Zucker", "Salz", "Weizenmehl Type 405", "Eiweiß", "Olivenöl"));
        recipes.add(Arrays.asList("\"Cannonballs\"  - Fleischbällchen aus der Fritteuse", "Hackfleisch", "Käse", "Frühstücksspeck", "Gewürz(e)", "Paniermehl", "Ei(er)", "Mehl", "Frittierfett"));
        recipes.add(Arrays.asList("\"Chicken of the Woods\" Schwefelporling-Nuggets", "Waldpilze", "Ei(er)", "Paniermehl", "Mehl", "Salz", "Pfeffer", "Öl"));
        recipes.add(Arrays.asList("\"Chinesischer\" Nudelauflauf", "Hackfleisch", "Salz und Pfeffer", "Sahne", "Käse, gerieben", "Mungobohnen", "Bambussprosse(n)", "Nudeln", "Möhre(n)", "Lauchstange(n)", "Paprikaschote(n), rot", "Gewürzmischung", "Pilze", "Fett für die Form"));
        recipes.add(Arrays.asList("\"Cholera\" - Schweizerische Lauch-Kartoffel-Käse-Pastete", "Mehl", "Salz", "Butter", "Wasser"));
        recipes.add(Arrays.asList("\"Chuck Wagon\" Eier-Kasserolle", "Ei(er)", "Mettwürstchen", "Zwiebel(n)", "Toastbrot", "Cheddarkäse", "Milch", "Pfeffer", "Senfpulver"));
        recipes.add(Arrays.asList("\"Chuck Wagon\" Maisbrot", "Maismehl", "Backpulver", "Salz", "Ei(er)", "Buttermilch", "Schmalz"));
        recipes.add(Arrays.asList("\"Cini Minis\" selbst gemacht", "Knäckebrot", "Zimt", "Süßstoff", "Milch"));
        recipes.add(Arrays.asList("\"Clotted Cream\" kalorienarm", "Schlagsahne", "Joghurt, griechischer"));
        recipes.add(Arrays.asList("\"Coburger Mohrenbrötchen\"", "Brötchen", "Butter", "Kuvertüre", "Kokosraspel"));
        recipes.add(Arrays.asList("\"Cocospresso\"", "Batida de Coco", "Espresso", "Eiswürfel"));
        recipes.add(Arrays.asList("\"Crispy Chicken\" Burger", "Hähnchenbrust", "Zwiebel(n)", "Knoblauchzehe(n)", "Pfefferkörner", "Meersalz", "Chilipulver", "Petersilie", "Tomate(n)", "Blattsalat", "Brötchen", "Crème fraîche", "Mayonnaise", "Cornflakes", "Ei(er)"));
        recipes.add(Arrays.asList("\"Dänischer\" Filettopf", "Schweinefilet(s)", "Champignons", "Fett", "Frischkäse", "Senf", "Sahne", "Estragon", "Weißwein", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Death by Chocolate\"", "Mehl", "Puderzucker", "Kakaopulver", "Salz", "Butter", "Zartbitterschokolade", "Ei(er)"));
        recipes.add(Arrays.asList("\"Death by Chocolate\" an heißer und kalter Mandel", "Zartbitterschokolade", "Butter", "Ei(er)", "Mehl", "Zucker", "Vanillezucker", "Salz"));
        recipes.add(Arrays.asList("\"Der Abend danach\" Grillfleisch-Auflauf", "Fleischreste", "Nudeln", "Zwiebel(n)", "Champignons", "Rotwein", "Tomatenmark", "Sahne", "Butter", "Käse, gerieben", "Naturjoghurt", "Ketchup", "Cayennepfeffer", "Kreuzkümmel", "Koriander"));
        recipes.add(Arrays.asList("\"Die deftigen 4\"", "Leberwurst", "Blutwurst", "Sauerkraut", "Kartoffel(n)", "Milch", "Kümmel", "Salz"));
        recipes.add(Arrays.asList("\"Dijon\"-Hähnchen", "Tomate(n)", "Gemüsezwiebel(n)", "Knoblauch", "Salz und Pfeffer", "Paprikapulver", "Oliven", "Creme", "Mandel(n)", "Hähnchenfilet(s)"));
        recipes.add(Arrays.asList("\"dreaming\" von gugel", "Wodka", "Brandy", "Grenadine", "Limettensaft", "Maracujasaft", "Saft", "Eis"));
        recipes.add(Arrays.asList("\"Eiersalat\" vegan", "Kichererbsen", "Nudeln", "Salzwasser", "Frühlingszwiebel(n)", "Kurkuma", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"EiJoLi\"", "Rapsöl", "Knoblauchzehe(n)", "Ei(er)", "Joghurt", "Salz", "Cayennepfeffer", "Chilipulver", "Limette(n)", "Olivenöl"));
        recipes.add(Arrays.asList("\"Einbrennte Hund\" mit Fisolen salzarm", "Kartoffel(n)", "Bohnen, grüne", "Natron", "Butter", "Mehl", "Milch", "Lorbeerblätter", "Knoblauchzehe(n)", "Essiggurke(n)", "Gurkenflüssigkeit", "Wurst", "Dill"));
        recipes.add(Arrays.asList("\"Einfach, aber oho!\"-Salatsauce", "Salz", "Kräutersalz", "Pfeffer", "Knoblauchgranulat", "Weißweinessig", "Senf, süßer", "Rapsöl", "Petersilie", "Schnittlauch"));
        recipes.add(Arrays.asList("\"Eisige\" Kaffeecreme", "Sahne", "Milch", "Ei(er)", "Kaffeepulver", "Salz", "Zucker", "Sahne", "Keks(e)"));
        recipes.add(Arrays.asList("\"el pavo\" mit Ingwer und Tomaten", "Truthahn", "Chilischote(n)", "Knoblauch", "Ingwerwurzel", "Tomate(n)", "Oregano", "Tomate(n)", "Olivenöl", "Gemüsezwiebel(n)", "Meersalz", "Pfeffer", "Limettenschale"));
        recipes.add(Arrays.asList("\"Ersatz\"-Tiramisu", "Löffelbiskuits", "süße Sahne", "Quark", "Mascarpone", "Eierlikör", "Apfelmus", "Zucker", "Amaretto"));
        recipes.add(Arrays.asList("\"Essbare Juwelen\"", "Wasser", "Agar-Agar", "Zucker", "Sirup", "Vanilleextrakt", "Lebensmittelfarbe"));
        recipes.add(Arrays.asList("\"Fake\" gefülltes Hähnchenbrustfilet mit Kartoffelecken", "Hähnchenbrustfilet(s)", "Kartoffel(n)", "Frischkäse", "Sahne", "Tomatenmark", "Cherrytomate(n)", "Öl", "Paprikapulver", "Currypulver", "Oregano", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Falsche Salsiccia\"", "Bratwürste", "Fenchelsamen", "Pfeffer"));
        recipes.add(Arrays.asList("\"Falsche\"  Macarons", "Keks(e)", "Mascarpone", "Sahne", "Kokosraspel"));
        recipes.add(Arrays.asList("\"Falsche\" Bratkartoffelpfanne", "Knollensellerie", "Paprika", "Champignons", "Zwiebel(n)", "Ketchup", "Ajvar", "Knoblauch", "Salz und Pfeffer", "Paprikapulver", "Gemüsebrühe"));
        recipes.add(Arrays.asList("\"Falsche\" Raffaellos", "Kondensmilch", "Kokosraspel", "Mandel(n)", "Waffeln"));
        recipes.add(Arrays.asList("\"Falscher Reissalat\" aus Blumenkohl", "Blumenkohl", "Tomate(n)", "Salatgurke(n)", "Frühlingszwiebel(n)", "Wurst", "Knoblauchzehe(n)", "Joghurt", "Mayonnaise", "Schnittlauch", "Salz", "Pfeffer"));
        recipes.add(Arrays.asList("\"Falscher\" Apfelkuchen", "Ei(er)", "Zucker", "Mehl", "Maisstärke", "Backpulver", "Wasser", "Apfelmus", "Sahne", "Mandel(n)", "Kakaopulver", "Früchte"));
        recipes.add(Arrays.asList("\"Falscher\" Elsässer Flammkuchen mit Blätterteig", "Blätterteig", "Crème fraîche", "Zwiebel(n)", "Schinken", "Basilikum"));
        recipes.add(Arrays.asList("\"Falscher\" Sauerbraten", "Rindfleisch", "Saucenkuchen", "Brühe", "Balsamico", "Zwiebel(n)", "Zucker", "Preiselbeerkompott", "Salz und Pfeffer", "Butterschmalz"));
        recipes.add(Arrays.asList("\"Falsches\" Erdbeertiramisu", "Keks(e)", "Puddingpulver", "Milch", "Zucker", "Erdbeeren", "Magerquark", "Joghurt", "Mandel(n)", "Likör", "Gelatinepulver", "Gelatinepulver", "Tortenguss"));
        recipes.add(Arrays.asList("\"Falsches\" Marzipan", "Mandel(n)", "Puderzucker", "Ei(er)", "Zitrone(n)"));
        recipes.add(Arrays.asList("\"Falsches\" Ossobuco", "Hähnchenschnitzel", "Staudensellerie", "Möhre(n)", "Zucchini", "Weißwein", "Geflügelfond", "Speck", "Zitrone(n)", "Basilikum", "Salbei", "Butter", "Zwiebel(n)"));
        recipes.add(Arrays.asList("\"Falsches\" Rahmgeschnetzeltes", "Schweinefilet(s)", "Schweineschmalz", "Zwiebel(n)", "Speckwürfel", "Champignons", "Butter", "Mehl", "Bratenfond", "Kokosmilch", "Paprikaschote(n), rot", "Zitronensaft", "Thymianzweig(e)", "Petersilie", "Muskat", "Paprikapulver", "Piment", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Faule\" Portweinbirne", "Birne(n)", "Portwein", "Nelke(n)"));
        recipes.add(Arrays.asList("\"Feiges Dessert\"", "Feige(n)", "Naturjoghurt", "Müsli", "Agavendicksaft", "Cashewkerne", "Cranberries", "Zimt"));
        recipes.add(Arrays.asList("\"Fettsuppe\" - Vorsuppe aus Rindfleisch, Beinscheibe und Sandknochen", "Rippe(n)", "Beinscheibe(n)", "Knochen", "Markknochen", "Suppengrün", "Salz", "Blumenkohl", "Nudeln"));
        recipes.add(Arrays.asList("\"Fisch\"stäbchen mit Vanillesoße", "Mandel(n)", "Butter", "Zucker", "Mehl", "Cornflakes"));
        recipes.add(Arrays.asList("\"Fischduftende\" Aubergine – Yu Xiang Qie Zi", "Aubergine(n)", "Öl zum Braten", "Ingwer", "Knoblauch", "Lauchzwiebel(n)", "Sojasauce", "Zucker", "Essig", "Sesamöl", "Wasser", "Maisstärke"));
        recipes.add(Arrays.asList("\"Flammkuchen\" nach Elsässer Art", "Zwiebel(n)", "Kräuterfrischkäse", "Käse", "Speckwürfel", "Pizzateig"));
        recipes.add(Arrays.asList("\"Fleischiges\" Veggie-Pesto", "Tomate(n), getrocknete", "Basilikumblätter", "Knoblauch", "Parmesan", "Mandelblättchen", "Olivenöl", "Pflanzenöl", "Salz und Pfeffer", "Chiliflocken"));
        recipes.add(Arrays.asList("\"Fohlenbrötchen\" - ein Muss für Borussen-Fans", "Weizenmehl Type 550", "Wasser", "Milch", "Hefe", "Salz", "Zucker", "Butter", "Ei(er)", "Sepiatinte"));
        recipes.add(Arrays.asList("\"Französische\" Pizza", "Mehl", "Butter", "Ei(er)", "Salz", "Wasser", "Senf, mittelscharfer", "Gouda", "Tomate(n)", "Zwiebel(n)", "Oliven", "Salz und Pfeffer", "Olivenöl", "Thymian", "Fett und Mehl für die Form"));
        recipes.add(Arrays.asList("\"Französischer\" Auflauf", "Kartoffel(n)", "Ei(er)", "Schinken", "Sahne", "Sauerrahm", "Salz und Pfeffer", "Rosmarin", "Käse"));
        recipes.add(Arrays.asList("\"Frühstücksmuffin\" Chicken and Egg", "Brötchen", "Ei(er)", "Burger Patties", "Cheddarkäse", "Bacon", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Gebackene\" grüne Bohnen", "Bohnen", "Zwiebel(n)", "Öl", "Bohnenkraut", "Petersilie", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Gefrostete\" Johannisbeertorte mit Baisers", "Ei(er)", "Puderzucker", "Öl", "Wasser", "Mehl", "Backpulver", "Konfitüre", "Johannisbeeren", "Zucker", "Zitrone(n)", "Gelatine", "Wasser", "Crème fraîche", "Sahne", "Johannisbeeren", "Eiweiß", "Zucker", "Schlagsahne", "Sahnesteif", "Walnüsse", "Baiser"));
        recipes.add(Arrays.asList("\"Gefüllter\" Kohl", "Weißkohl", "Salz", "Fondor", "Butter"));
        recipes.add(Arrays.asList("\"Gehackter Molly\" Falscher Hase aus dem Römertopf", "Rinderhackfleisch", "Brötchen", "Zwiebel(n)", "Ei(er)", "Salz und Pfeffer", "Majoran", "Oregano", "Gouda", "Bacon", "Fleischtomate(n)", "Brühe", "Saucenbinder", "Paniermehl"));
        recipes.add(Arrays.asList("\"Gehopste\" Kartoffeln nach Ostpreußenart", "Kartoffel(n)", "Schmand", "Petersilie", "Salz", "Pfeffer"));
        recipes.add(Arrays.asList("\"Gelbes\"", "Reis", "Putenfleisch", "Banane(n)", "Pfirsich(e)", "Sambal Oelek", "Sahne", "Kurkuma", "Currypulver", "Salz", "Pfeffer", "Butter"));
        recipes.add(Arrays.asList("\"Geschnätzlets Wunder\" - Schweizer Rezept à la BB", "Fett", "Hähnchenbrust", "Salz", "Cognac", "Butter", "Zwiebel(n)", "Knoblauchzehe(n)", "Rosmarin", "Paprikapulver", "Currypulver", "Ketchup", "Weißwein", "Hühnerbrühe", "Maisstärke", "Rahm"));
        recipes.add(Arrays.asList("\"Geschwärzter\" Lachs mit Fenchelpüree und Ofengemüse", "Lachs", "Paprikapulver", "Oregano", "Knoblauch", "Kartoffel(n)", "Fenchel", "Frühlingszwiebel(n)", "Butter", "Gemüse", "Olivenöl", "Kräuter"));
        recipes.add(Arrays.asList("\"Gestopfter Müller\"", "Zwiebel(n)", "Margarine", "Mehl", "Ketchup", "Senf", "Schnittlauchröllchen", "Zucker"));
        recipes.add(Arrays.asList("\"Gesunde\" Hollandaise", "Butter", "Mehl", "Gemüsebrühe", "Milch", "Zitronensaft", "süße Sahne", "Eigelb", "Salz"));
        recipes.add(Arrays.asList("\"Gesunde\", fruchtige Plätzchen", "Dinkelvollkornmehl", "Weizenmehl", "Mehl", "Zucker", "Süßstoff", "Butter", "Eigelb", "Zitronensäure", "Orangenschalenaroma", "Vanille"));
        recipes.add(Arrays.asList("\"Giotto\"-Pralinen", "Kondensmilch", "Haselnüsse", "Nutella", "Haselnüsse", "Kuvertüre", "Kuchenglasur"));
        recipes.add(Arrays.asList("\"Giotto-Eis\"", "Konfekt", "Ei(er)", "Likör", "Sirup", "Schlagsahne", "Salz"));
        recipes.add(Arrays.asList("\"Gönn dir\"-Burger mit Camembert und Reibekuchen", "Croissant(s)", "Salatcreme (Miracel Whip)", "Chiliflocken", "Romanasalatherz(en)", "Kartoffelpuffer", "Bacon", "Camembert(s)", "Wildpreiselbeeren"));
        recipes.add(Arrays.asList("\"Grüner Fusel\"", "Maracujasaft", "Saft", "Rum", "Weinbrand", "Batida de Coco", "Blue Curaçao"));
        recipes.add(Arrays.asList("\"Gschnittna Hoosn\"", "Mehl", "Backpulver", "Ei(er)", "Rahm", "Butter", "Arrak", "Zucker", "Zucker", "Zimt", "Butter"));
        recipes.add(Arrays.asList("\"Gute Laune\"-Geschnetzeltes", "Hühnerbrust", "Zwiebel(n)", "Knoblauch", "Rapsöl", "Zucchini", "Gemüsebrühe", "Sauerrahm", "Stärkemehl", "Salz und Pfeffer", "Kräuter"));
        recipes.add(Arrays.asList("\"Guten Morgen\" Fruchtsmoothie", "Himbeeren", "Erdbeeren", "Beeren", "Erdbeersaft", "Milch", "Zimtpulver"));
        recipes.add(Arrays.asList("\"Hackfleisch\"-Sauce aus Tofu", "Tofu", "Zwiebel(n)", "Sojasauce", "Öl", "Gemüsebrühe", "Pfeffer", "Paprikapulver", "Knoblauchzehe(n)", "Tomate(n)", "Tomatenmark", "Paprikamark", "Wasser"));
        recipes.add(Arrays.asList("\"Hackfleisch-Pizza\" etwas anders", "Hackfleisch", "Tomaten, stückige", "Salz", "Paprikapulver", "Kräuter", "Paprika", "Zucchini", "Champignons", "Nudeln", "Tomatenketchup", "Käse, gerieben"));
        recipes.add(Arrays.asList("\"Hähnchen Brasil\" aus dem Backofen", "Hähnchenbrustfilet(s)", "Gewürzmischung", "Cremefine", "Champignons", "Knoblauchzehe(n)", "Rapsöl", "Emmentaler"));
        recipes.add(Arrays.asList("\"Halbkorn\" - Brötchen von gugel", "Weizenmehl", "Weizenmehl", "Salz", "Honig", "Backmalz", "Hefe", "Wasser", "Sonnenblumenkerne"));
        recipes.add(Arrays.asList("\"Hannes\" Salat", "Suppenfleisch", "Kartoffel(n)", "Bismarckhering(e)", "Ei(er)", "Rote Bete", "Sellerie", "Mayonnaise", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Heiße\" gegrillte Spare Ribs mit Paprika-Anis-Buttergemüse", "Honig", "Maggi", "Ketchup", "Weißweinessig", "Weißwein", "Öl", "Senfpulver", "Rippchen", "Gemüsezwiebel(n)", "Paprikaschote(n)", "Paprikaschote(n)", "Paprikaschote(n)", "Butter", "Anis", "Pfeffer", "Salz", "Chilipulver"));
        recipes.add(Arrays.asList("\"Heißer Feger\" - Lakritze ganz anders", "Lakritze", "Lakritze", "Chilischote(n)", "Ingwer", "Orange(n)", "Zucker", "Wasser"));
        recipes.add(Arrays.asList("\"Himmel un Ääd\"  mit Putenleber – der NRW-Klassiker mal anders", "Putenleber", "Pellkartoffel(n)", "Äpfel", "Schalotte(n)", "Frühlingszwiebel(n)", "Crème fraîche", "Milch", "Käse", "Salz", "Pfeffer", "Fett", "Fett"));
        recipes.add(Arrays.asList("\"Himmel und Erde\", abgewandelt  für das kalte Büffet", "Kartoffel(n)", "Blutwurst", "Apfel", "Schalotte(n)", "Öl", "Salat", "Senf", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Hot Dog\" Fisch", "Fischfilet(s)", "Ketchup", "Gewürzgurke(n)", "Röstzwiebeln", "Käse", "Salz", "Pfeffer", "Senf"));
        recipes.add(Arrays.asList("\"I need a hug\" -  Erdnussbutter Kekse", "Butter", "Erdnussbutter", "Zucker", "Zucker", "Weizenmehl", "Ei(er)", "Salz", "Backpulver", "Natron"));
        recipes.add(Arrays.asList("\"Iss mich auf\" Kuchen", "Ei(er)", "Zucker", "Öl", "Backpulver", "Mehl", "Orangenlimonade", "Cremepulver", "Sahne", "Butter", "Zucker", "Walnüsse", "Schokoglasur"));
        recipes.add(Arrays.asList("\"Italienische\" Maultaschen", "Maultaschen", "Tomate(n)", "Mozzarella", "Basilikum", "Knoblauch", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Käse\"-Nudeln", "Vollkornnudeln", "Cashewnüsse", "Wasser", "Zitrone(n)", "Sonnenblumenkerne", "Hefeflocken", "Salz", "Paprika", "Möhre(n)", "Tomate(n)", "Öl", "Semmelbrösel"));
        recipes.add(Arrays.asList("\"Käsekuchen\" aus Sojaquark", "Dinkelmehl Type 1050", "Sonnenblumenöl", "Rohrohrzucker", "Weinsteinbackpulver", "Wasser", "Fett für die Form", "Mehl für die Form"));
        recipes.add(Arrays.asList("\"Käsige\" Blumenkohlsuppe", "Blumenkohl", "Zwiebel(n)", "Knoblauchzehe(n)", "Gemüsebrühe", "Hefeflocken", "Öl", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Katzengeschrei\" Bratkartoffeln mit grober Leberwurst", "Kartoffel(n)", "Leberwurst", "Salz", "Pfeffer", "Fondor", "Paprikapulver", "Zwiebel(n)", "Öl"));
        recipes.add(Arrays.asList("\"Kieler\"", "Hähnchenbrustfilet(s)", "Paprikaschote(n)", "Sahne", "Doppelrahmfrischkäse", "Reis", "Öl", "Salzwasser", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Klassische Lasagne\" mit Kartoffeln statt Nudeln", "Kartoffel(n)", "Hackfleisch", "Zwiebel(n)", "Knoblauchzehe(n)", "Tomate(n)", "Blattspinat", "Ricotta", "Pinienkerne", "Mehl", "Butter", "Milch", "Käse", "Salz und Pfeffer", "Muskat", "Rosmarin", "Thymian", "Öl"));
        recipes.add(Arrays.asList("\"Kleine Schuhe \" aus Auberginen", "Aubergine(n)", "Milch", "Butter", "Mehl", "Muskat", "Ei(er)", "Käse", "Zwiebel(n)", "Tomate(n)", "Hackfleisch", "Olivenöl", "Butter", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Kleines Weißes\"", "Hefe", "Salz", "Honig", "Dinkelmehl"));
        recipes.add(Arrays.asList("\"Komme Djoosh\" - persisches Rezept mit Quark und Kurkuma", "Quark", "Wasser", "Ei(er)", "Kurkumapulver", "Zwiebel(n)", "Tomate(n)", "Öl", "Butter", "Walnüsse", "Salz und Pfeffer", "Brötchen"));
        recipes.add(Arrays.asList("\"Kostet fast nix\"-Nudelpfanne", "Nudeln", "Kochschinken", "Erbsen", "Paprikaschote(n)", "Crème légère", "Gemüsebrühe", "Salz", "Pfeffer", "Kräuter"));
        recipes.add(Arrays.asList("\"Kotelett\" persisch", "Hackfleisch", "Kartoffel(n)", "Zwiebel(n)", "Ei(er)", "Kurkuma", "Salz und Pfeffer", "Paniermehl", "Öl zum Braten"));
        recipes.add(Arrays.asList("\"Krawall-Creme\" - Käse-Knoblauch-Dip", "Feta-Käse", "Mozzarella", "Käse", "Crème fraîche", "Mayonnaise", "Knoblauch", "Salz und Pfeffer", "Paprikapulver"));
        recipes.add(Arrays.asList("\"Kühlschrank-Spätlese\" - Grillfleisch-Eintopf", "Fleisch", "Zucchini", "Champignons", "Speck", "Tomatenmark", "Kidneybohnen", "Mais", "Zwiebel(n)", "Fleischbrühe", "saure Sahne", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Lachs-Sushi\" auf europäische Art", "Reis", "Essig", "Zucker", "Fondor", "Räucherlachs", "Meerrettich", "Schnittlauch", "Sojasauce"));
        recipes.add(Arrays.asList("\"Latschen\"-Kartoffelpuffer", "Kartoffel(n)", "Kartoffel(n)", "Quark", "Ei(er)", "Salz", "Kümmel", "Rapsöl"));
        recipes.add(Arrays.asList("\"Leberwurst\" vegan", "Kidneybohnen", "Räuchertofu", "Öl", "Zwiebel(n)", "Knoblauchzehe(n)", "Marmelade", "Majoran", "Oregano", "Pimentkörner", "Salz und Pfeffer", "Zitronensaft", "Rauchsalz"));
        recipes.add(Arrays.asList("\"Magic Dust'' Spareribs", "Rippe(n)", "Gewürzmischung", "Apfelessig", "Apfelsaft", "Cola", "Sauce"));
        recipes.add(Arrays.asList("\"Mensch ärgere dich nicht\" - Torte", "Margarine", "Zucker", "Ei(er)", "Mehl", "Vanillezucker", "Backpulver", "Schokolade"));
        recipes.add(Arrays.asList("\"Mittelschnelles\" Lammragout mit Tomaten und Champignons", "Lammfleisch", "Zwiebel(n)", "Knoblauch", "Tomate(n)", "Tomate(n)", "Champignons", "Tomatenmark", "Paprikamark", "Rotwein", "Salz und Pfeffer", "Rosmarin", "Cayennepfeffer", "Piment", "Öl", "Crème fraîche"));
        recipes.add(Arrays.asList("\"Mousse au Chocolat\", vegane Schokocreme aus Bananen", "Banane(n)", "Avocado(s)", "Nussmus", "Pflanzenmilch (Pflanzendrink)", "Kakaopulver"));
        recipes.add(Arrays.asList("\"Nackte\" chinesische Entenbrust mit \"Knurpseln\"", "Entenbrust"));
        recipes.add(Arrays.asList("\"Nordböhe\" - Hackfleisch-Reis-Käse-Pfanne", "Hackfleisch", "Langkornreis", "Speckwürfel", "Feta-Käse", "Käse", "Paprikaschote(n)", "Peperoni", "Mais", "Knoblauch", "Zwiebel(n)", "Schmand", "Crème fraîche", "Currypulver", "Paprikapulver", "Salz und Pfeffer", "Basilikumblätter"));
        recipes.add(Arrays.asList("\"Nordica\" Bowl", "Reis", "Wasser", "Salz", "Kopfsalat(e)", "Möhre(n)", "Petersilie", "Stremellachs", "Salatcreme", "Wasabipaste"));
        recipes.add(Arrays.asList("\"Nordsee Sushi\" - Kürbis mit Matjes", "Kürbisfleisch", "Matjesfilet(s)", "Rote Bete", "Salzwasser", "Pfeffer"));
        recipes.add(Arrays.asList("\"Nürnberger\" Kartoffel-Gemüse-Eintopf", "Zwiebel(n)", "Suppengrün", "Kartoffeln, festkochend", "Speck", "Nürnberger Rostbratwürstchen", "Gemüsebrühe", "Salz und Pfeffer, schwarzer", "Erbsen, TK", "Kartoffelpüreepulver", "Oregano", "Kerbel"));
        recipes.add(Arrays.asList("\"Oh happy day!\" - Mug Cake Grundrezept", "Mehl", "Zucker", "Milch", "Backpulver", "Ei(er)", "Salz"));
        recipes.add(Arrays.asList("\"Orangener Matsch\" - Süßkartoffel-Möhren-Kidneybohnenbrei", "Süßkartoffel(n)", "Möhre(n)", "Kidneybohnen", "Rapsöl"));
        recipes.add(Arrays.asList("\"Orangentorte\" im Glas", "Sahne", "Magerquark", "Orange(n)", "Vollkorn-Butterkekse", "Vanillezucker", "Erythrit (Zuckerersatz)", "Zitronenschale", "Orangenmarmelade", "Wasser"));
        recipes.add(Arrays.asList("\"Ostereis\" aus Osterhasen oder Kinderschokolade", "Schokolade", "H-Milch", "Sahne", "Ei(er)", "Zucker"));
        recipes.add(Arrays.asList("\"Ötzis\" Kirchtagskrapfen", "Butter", "Mehl", "Ei(er)", "Eigelb", "Wasser", "Salz", "Schmalz"));
        recipes.add(Arrays.asList("\"Pamela\"", "Grapefruitsaft", "Minzeblätter", "Sekt"));
        recipes.add(Arrays.asList("\"Panierte\" Nuss-Spätzle", "Spätzle", "Haselnüsse", "Butter", "Salz"));
        recipes.add(Arrays.asList("\"Papa isst die Pfanne leer\"", "Schalotte(n)", "Kartoffel(n)", "Zucchini", "Paprikaschote(n)", "Champignons", "Ei(er)", "Milch", "Sahne", "Kräuter", "Salz und Pfeffer", "Paprikapulver", "Regensburger Würste"));
        recipes.add(Arrays.asList("\"Paprikasch\" mit Kartoffelpüree", "Schweineschnitzel", "Paprikaschote(n)", "Paprikaschote(n)", "Paprikaschote(n)", "Zwiebel(n)", "Tomatenmark", "Paprikapaste", "Wasser", "Kartoffel(n)", "Milch", "Butter", "Röstzwiebeln", "Schnittlauch", "Salz und Pfeffer", "Thymian", "Paprikapulver", "Muskat", "Öl zum Braten"));
        recipes.add(Arrays.asList("\"Pie\" mit Thunfisch", "Frischkäse", "Ei(er)", "Paprikaschote(n)", "Zucchini", "Zwiebel(n)", "Thunfisch", "Käse", "Salz"));
        recipes.add(Arrays.asList("\"Pilz-Ketchup\" - Pilzsauce und Pilzgewürz nach einem Rezept aus dem 18. Jahrhundert", "Champignons", "Salz", "Lorbeerblätter", "Zwiebel(n)", "Zitrone(n)", "Meerrettich", "Nelke(n)", "Muskatnuss", "Zimt", "Pfeffer, schwarzer", "Rohrohrzucker", "Apfelessig"));
        recipes.add(Arrays.asList("\"Pinke Versuchung\" - Birnen-Blaukraut-Marmelade mit Prosecco", "Birne(n)", "Blaukraut", "Zitrone(n), Saft davon", "Gelierzucker 3:1", "Prosecco", "Gewürznelke(n)", "Pimentkörner", "Kardamomkapsel(n)", "Zimt", "Vanilleschote(n)", "Chilischote(n)"));
        recipes.add(Arrays.asList("\"Pizza\" - mal anders", "Hähnchenbrust", "Ei(er)", "Paprika", "Sonnenblumenkerne", "Romanasalat", "Rispentomate(n)", "Quark", "Kräuter"));
        recipes.add(Arrays.asList("\"Plumpskuchen\" bzw. Kirsch-Nougatkuchen ohne Backen", "Nougat", "Zwieback", "Sauerkirschen", "Speisestärke", "Schlagsahne", "Amaretto"));
        recipes.add(Arrays.asList("\"Pommes\" aus Schnitzelfleisch", "Schweineschnitzel"));
        recipes.add(Arrays.asList("\"Prager Salat\" mit Kartoffeln und pochiertem Ei", "Blattsalat", "Kartoffel(n)", "Bohnen, grüne", "Tomate(n)", "Gurke(n)", "Zwiebel(n)", "Ei(er)"));
        recipes.add(Arrays.asList("\"Prickelnd\" würziger Brotaufstrich", "Knoblauch", "Lauchzwiebel(n)", "Zwiebel(n)", "Olivenöl", "Sonnenblumenkerne", "Chilischote(n)", "Frischkäse", "Soja", "Gemüsebrühwürfel", "Wasser", "Ajvar", "Kurkuma", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Prugny\" Pflaumenkuchen ohne Ei", "Zucker", "Butter", "Vanillezucker", "Magerjoghurt", "Mehl", "Backpulver", "Milch", "Salz", "Pflaume(n)", "Zimt", "Zucker"));
        recipes.add(Arrays.asList("\"Pulled\" Kasseler aus dem Römertopf", "Kasselernacken"));
        recipes.add(Arrays.asList("\"Pumpkina\" Kuchen", "Banane(n)", "Ei(er)", "Hokkaidokürbis(se)", "Zimtpulver", "Kardamompulver", "Mandel(n)"));
        recipes.add(Arrays.asList("\"Queimada\" Quemada Galega", "Brandy", "Zucker", "Rosinen", "Apfel", "Kaffeebohnen", "Rum", "Rotwein", "Zimt", "Zitrone(n)"));
        recipes.add(Arrays.asList("\"Rancher's\" Buttermilch-Mayonnaise Dressing", "Buttermilch", "Mayonnaise", "Knoblauchzehe(n)", "Petersilie", "Oregano", "Salz", "Pfeffer, schwarzer", "Schalotte(n)"));
        recipes.add(Arrays.asList("\"Ratatouille\"-Topf mit Halloumi", "Zucchini", "Pastinake(n)", "Möhre(n)", "Paprikaschote(n), gelb", "Porree", "Ingwer", "Lorbeerblätter", "Olivenöl", "Tomaten, geschälte", "Oregano", "Thymian", "Basilikum", "Rosmarin", "Bärlauchblätter", "Gemüsebrühe", "Halloumi", "Salz und Pfeffer, schwarzer", "Pimentón de la Vera", "Petersilie", "Zitronenabrieb"));
        recipes.add(Arrays.asList("\"Rote Grütze\" Marmelade", "Himbeeren", "Brombeeren", "Johannisbeeren", "Stachelbeeren", "Jostabeeren", "Taybeeren", "Erdbeeren", "Holunderbeeren", "Gelierzucker 2:1"));
        recipes.add(Arrays.asList("\"Rote\" Nudelpfanne mit Fetakäse", "Nudeln", "Paprikaschote(n)", "Tomate(n)", "Feta-Käse", "Zucker", "Pilze", "Chili", "Salz", "Pfeffer", "Oregano", "Öl", "Gemüsebrühe", "Wasser"));
        recipes.add(Arrays.asList("\"Rumfort\"-Kartoffel-Gemüsepfanne mit Bratwurst", "Bratwurst", "Kartoffel(n)", "Buschbohnen", "Möhre(n)", "Lauchzwiebel(n)", "Radieschen", "Zwiebel(n), rot", "Knoblauch", "Salz und Pfeffer", "Rapsöl"));
        recipes.add(Arrays.asList("\"Rumfort\"-Pfanne für 2 Personen  (alles, was RUM liegt und FORT muss)", "Kartoffel(n)", "Kohlrabi", "Spitzpaprika", "Radieschen", "Fleischwurst", "Champignons", "Salz", "Pfeffer", "Chiliflocken", "Fett"));
        recipes.add(Arrays.asList("\"Salzige\" Traubentorte von Ulla", "Blätterteig", "Weintrauben", "Ei(er)", "Schmand", "Käse", "Salz und Pfeffer", "Paprikapulver", "Petersilie"));
        recipes.add(Arrays.asList("\"Schlanke\" Hollandaise", "Rapsöl", "Weizenmehl", "Milch", "Brühe", "Zitronensaft", "Salz", "Pfeffer"));
        recipes.add(Arrays.asList("\"Schlankes\" Tiramisu", "Löffelbiskuits", "Magerquark", "Cremefine", "Vanillezucker", "Zucker", "Kaffee", "Weinbrand", "Zartbitterschokolade", "Mineralwasser"));
        recipes.add(Arrays.asList("\"Schnitzelpizza\" Hawaii", "Zwiebel(n)", "Olivenöl", "Salz", "Pfeffer", "Zucker", "Paprikapulver, edelsüß", "Tomate(n)", "Gemüsebrühe", "Schlagsahne", "Ananas", "Schweineschnitzel", "Kochschinken", "Gouda", "Majoran"));
        recipes.add(Arrays.asList("\"Schokopudding\" für jede Diät", "Magerquark", "Banane(n)", "Backkakao", "Mineralwasser"));
        recipes.add(Arrays.asList("\"Schulten-Salat\"", "Rucola", "Tomate(n)", "Kirschtomate(n)", "Feta-Käse", "Pinienkerne", "Gnocchi", "Schinken", "Parmesan"));
        recipes.add(Arrays.asList("\"Schweinerei\" mit zweierlei Roter Bete und Rettichfond", "Schweinebäckchen", "Salz", "Pfeffer", "Gänseschmalz", "Rosmarin", "Knoblauch", "Butter"));
        recipes.add(Arrays.asList("\"Slippery When Wet\" à la Shannon Tebay Sidle", "Erdbeere", "Zitronensaft", "Honig, flüssiger", "Gin", "Joghurt, griechischer", "Crushed Ice", "Pfeffer, schwarzer", "Erdbeere"));
        recipes.add(Arrays.asList("\"Snickers\"-Bananenkuchen", "Tortenboden", "Banane(n)", "Erdnussbutter", "Aufstrich"));
        recipes.add(Arrays.asList("\"Snickers\"-Eis", "Schokoriegel", "Likör", "süße Sahne", "Gelatine", "Eigelb"));
        recipes.add(Arrays.asList("\"Spanische Milch\" à la Gabi", "Butter", "Mehl", "Zucker", "Milch", "Ei(er)", "Weißbrot", "Öl", "Ei(er)", "Puderzucker", "Zimtstange(n)", "Orange(n)"));
        recipes.add(Arrays.asList("\"Spätzliflette\" - Schwäbische Variante von Tartiflette", "Spätzle", "Speck", "Sahne", "Weichkäse", "Zwiebel(n)", "Weißwein", "Butter für die Form"));
        recipes.add(Arrays.asList("\"Spinat\" aus Kapuzinerkresseblättern", "Kapuzinerkresseblätter", "Schalotte(n)", "Schlagsahne", "Parmesan, gerieben", "Olivenöl", "Muskatnuss", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("\"Sportler\"-Cocktail", "Tomate(n)", "Salatgurke(n)", "Äpfel", "süße Sahne", "Petersilie", "Eiswürfel"));
        recipes.add(Arrays.asList("\"Sprite\"-Sirup", "Zitrone(n)", "Zucker"));
        recipes.add(Arrays.asList("\"Strammer Max\" Breze", "Brezel(n)", "Emmentaler", "Kochschinken", "Ei(er)", "Schnittlauch"));
        recipes.add(Arrays.asList("\"Tarzanessen\" - macht Kinder groß und stark", "Hackfleisch", "Rapsöl", "Zwiebel(n)", "Möhre(n)", "Reis", "Paprikapulver", "Currypulver", "Salz und Pfeffer", "Salat", "Paprikaschote(n)", "Möhre(n)", "Dressing", "Sojasauce"));
        recipes.add(Arrays.asList("\"Thai Kabeljau\"-Suppe", "Zitronengras", "Lauchzwiebel(n)", "Chilischote(n)", "Limette(n)", "Thai-Basilikum", "Koriander", "Fischsauce", "Sesamöl", "Kabeljau", "Currypaste", "Kokosmilch", "Salz"));
        recipes.add(Arrays.asList("\"Tomatensuppe tropisch\" mit Mango und Ingwer", "Tomate(n)", "Zwiebel(n)", "Ingwerwurzel", "Öl", "Currypulver", "Kurkuma", "Gemüsebrühe", "Mango(s)", "Limette(n)", "Marmelade", "Salz und Pfeffer", "Schinken"));
        recipes.add(Arrays.asList("\"Tre colore\" Salat", "Kohlrabi", "Möhre(n)", "Zwiebel(n)", "Mais", "Olivenöl", "Weißweinessig", "Salz und Pfeffer", "Paprikapulver", "Brunnenkresse"));
        recipes.add(Arrays.asList("\"Türkisches Frühstück\"", "Tomate(n)", "Paprikaschote(n)", "Salatgurke(n)", "Joghurt", "Zwiebel(n)", "Knoblauchzehe(n)", "Hirse", "Tomatenmark", "Salz und Pfeffer", "Öl", "Kreuzkümmel", "Minze", "Gemüsebrühe", "Fladenbrot(e)"));
        recipes.add(Arrays.asList("\"Typisch deutscher\" Nudelsalat - vegan", "Nudeln", "Salzwasser", "Sojasahne (Sojacreme Cuisine)", "Räuchertofu", "Erbsen", "Mais", "Lauchzwiebel(n)", "Pflanzenöl", "Zitrone(n)", "Rotweinessig", "Salz und Pfeffer", "Maggi", "Cayennepfeffer"));
        recipes.add(Arrays.asList("\"Überraschungseier\" mit marinierten Erdbeeren", "Süßigkeiten"));
        recipes.add(Arrays.asList("\"Uncle Mike's\" Frühstücks-Kekse", "Wasser", "Backpulver", "Kartoffel(n)", "Butter", "Ei(er)", "Weizenmehl", "Salz", "Zucker, braun"));
        recipes.add(Arrays.asList("\"Ungarische\" Kartoffel-Gulaschsuppe mit Mehlklößchen", "Kartoffel(n)", "Wurst", "Mehl", "Salz", "Wasser", "Wasser", "Paprikapulver, edelsüß", "Öl zum Braten"));
        recipes.add(Arrays.asList("\"Unsichtbarer\" Schokoladenapfelkuchen", "Apfel", "Butter", "Zucker", "Schokolade", "Mehl", "Ei(er)", "Kakaopulver", "Backpulver", "Salz", "Haselnüsse", "Puderzucker"));
        recipes.add(Arrays.asList("\"Verheierte\" vegetarisch", "Kartoffel(n)", "Mehl", "Ei(er)", "Wasser", "Salz", "Zwiebel(n)", "Butterschmalz"));
        recipes.add(Arrays.asList("\"Verkehrte\" Lasagne", "Hackfleisch", "Ei(er)", "Knoblauchzehe(n)", "Zwiebel(n)", "Zucchino", "Paprikaschote(n)", "Fleischtomate(n)", "Lasagneplatte(n)", "Mehl", "Butter", "Milch", "Käse, gerieben", "Öl", "Öl zum Braten", "Salz und Pfeffer", "Chilipulver", "Paprikapulver", "Kräuter, italienische", "Semmelbrösel"));
        recipes.add(Arrays.asList("\"Verprügelte\" Schlangengurke", "Schlangengurke(n)", "Salz", "Zucker"));
        recipes.add(Arrays.asList("\"Vöner\"", "Fladenbrot(e)", "Sojaschnetzel", "Rotkohl", "Zwiebel(n)", "Sojajoghurt (Joghurtalternative)", "Knoblauchzehe(n)", "Gurke(n)", "Tomate(n)", "Eisbergsalat", "Gyrosgewürz", "Zucker", "Salz und Pfeffer", "Essigessenz", "Gemüsebrühe", "Mineralwasser", "Olivenöl"));
        recipes.add(Arrays.asList("\"Weihnachtskeks\"-Drink ohne Zuckerzusatz", "Mandel(n)", "Nelkenpulver", "Zimtpulver", "Ingwerpulver", "Vanilleschote(n)", "Soft-Feigen", "Soft-Datteln", "Milch", "Wasser"));
        recipes.add(Arrays.asList("\"weiße\" Pizza Bianca", "Mehl", "Wasser", "Olivenöl", "Salz", "Crème fraîche", "Zwiebel(n)", "Bacon", "Rucola", "Salz und Pfeffer", "Backpapier"));
        recipes.add(Arrays.asList("\"Wilde\" Cannelloni in rot-weißer Sauce", "Cannelloni", "Gehacktes", "Parmesan", "Zwiebel(n)", "Kapern", "Brötchen", "Olivenöl", "Knoblauch", "Rosmarin", "Thymian", "Weißwein", "Oregano", "Salz", "Pfeffer", "Tomate(n)", "Tomate(n)", "Piment", "Salz", "Zucker", "Sahne", "Parmesan", "Mozzarella"));
        recipes.add(Arrays.asList("\"Wilder Hos\" - Feldhase mit leckerer Soße auf Rehauer Art", "Hase(n)", "Salz und Pfeffer", "Wacholderbeere(n)", "Speck", "Butter", "Lorbeerblatt", "Zwiebel(n)", "Karotte(n)", "Petersilienwurzel(n)", "Brühwürfel", "süße Sahne", "saure Sahne", "Gelee", "Zucker", "Essig", "Rotwein", "Wasser"));
        recipes.add(Arrays.asList("\"Wintersmoothie\"", "Feige(n)", "Backpflaume(n)", "Rosinen", "Johannisbeeren", "Postelein"));
        recipes.add(Arrays.asList("\"Winzertorte\" à la Gabi", "Mehl", "Eigelb", "Salz", "Wasser", "Butter"));
        recipes.add(Arrays.asList("\"Wurzelpeter\" Suppe", "Möhre(n)", "Petersilienwurzel(n)", "Pastinake(n)", "Brokkoli", "Zwiebel(n)", "Kartoffel(n)", "Wasser", "Rapsöl", "Gemüsebrühe", "Salz", "Majoran"));
        recipes.add(Arrays.asList("\"Zack zack\" Hack mit Paprika und Kartoffeln", "Hackfleisch", "Paprika", "Kartoffel(n)", "Salz", "Pfeffer", "Paprikapulver", "Brühwürfel", "Wasser"));
        recipes.add(Arrays.asList("\"Zweiundsiebziger\", großes Weizenmischbrot mit Weizensauerteig und Roggensauerteig, 72% Weizenmehl", "Weizenmehl Type 550", "Roggenmehl Type 1370", "Wasser", "Öl", "Sirup", "Salz", "Weizenanstellgut", "Roggenanstellgut", "Mehl"));
        recipes.add(Arrays.asList("''Fantasie''-Torte", "Tortenboden", "Cremepulver", "Pfirsich(e)", "Tortenguss"));
        recipes.add(Arrays.asList("'Ab in den Backofen' - Hühnchen", "Hühnerbrüste", "Salz und Pfeffer", "Knoblauch"));
        recipes.add(Arrays.asList("'Alles was da ist' - Eintopf", "Kartoffel(n)", "Kasseler", "Linsen", "Bohnen", "Gemüse", "Brühe", "Gewürz(e)", "Würste"));
        recipes.add(Arrays.asList("'Ameisen auf dem Baum' oder 'Knisterndes Gemüse - Rindfleisch mit Glasnudeln'", "Glasnudeln", "Rinderfilet(s)", "Zwiebel(n)", "Sojasauce", "Sherry", "Öl", "Speisestärke", "Zucker", "Öl", "Brühe", "Wasser", "Ingwerpulver", "Lauch", "Möhre(n)", "Paprikaschote(n)"));
        recipes.add(Arrays.asList("'Apotheke'", "Likör", "Wermut", "Likör"));
        recipes.add(Arrays.asList("'Basilikum Schnittkäse' vegan", "Nüsse", "Speisestärke", "Mehl", "Zitronensaft", "Senf", "Sesampaste", "Tomatenmark", "Meersalz", "Knoblauch", "Sojadrink", "Wasser", "Agar-Agar", "Basilikum", "Olivenöl"));
        recipes.add(Arrays.asList("'Besser als Sex' - Kuchen", "Butter", "Zucker", "Ei(er)", "Mehl", "Kakaopulver", "Backpulver", "Milch", "Ananasscheibe(n)", "Zucker", "Banane(n)", "Aprikose(n)", "Tortenguss", "Vanillepuddingpulver", "Vanillinzucker", "Milch", "Schlagsahne", "Sahnesteif", "Nüsse"));
        recipes.add(Arrays.asList("'Bissige' Erdnussplätzchen - besonders knackig durch ganze Erdnüsse", "Butter", "Mehl", "Zucker", "Salz", "Ei(er)", "Backpulver", "Zimt", "Erdnusscreme", "Erdnüsse"));
        recipes.add(Arrays.asList("'Blutiges' Ratatouille", "Paprikaschote(n)", "Zwiebel(n)", "Zucchini", "Tomate(n)", "Tomatenmark", "Wasser", "Salz und Pfeffer", "Thymian", "Rosmarin", "Lorbeerblatt"));
        recipes.add(Arrays.asList("'Böse' Brötchen", "Brötchen", "Kochschinken", "Salami", "Gemüse", "Käse", "Schlagsahne", "Tabasco"));
        recipes.add(Arrays.asList("'Bratapfelmus' nach Monchimädchenart", "Äpfel", "Süßigkeiten", "Wasser"));
        recipes.add(Arrays.asList("'Cai-Uwe' Cocktail", "Likör", "Apfelsaft", "Sekt", "Zucker", "Zitrone(n)", "Eiswürfel"));
        recipes.add(Arrays.asList("'Cherry Turnover'", "Zucker", "Butter", "Mehl", "Salz", "Schattenmorellen", "Milch", "Puderzucker"));
        recipes.add(Arrays.asList("'Chinesisch'", "Nudeln", "Hackfleisch", "Lauch", "Champignons", "Zwiebel(n)", "Salz", "Gewürzmischung", "Sojasauce"));
        recipes.add(Arrays.asList("'Chinesische' Nudeln", "Penne", "Wasser", "Möhre(n)", "Zucchini", "Paprikaschote(n)", "Zwiebel(n)", "Salz und Pfeffer", "Gewürzmischung", "Sojasauce", "Knoblauch", "Gemüsebrühe", "Öl", "Chilischote(n)"));
        recipes.add(Arrays.asList("'Chinesischer'  Spaghettisalat", "Spaghetti", "Lauch", "Paprikaschote(n)", "Gewürzmischung", "Sojasauce", "Zitronensaft", "Salz und Pfeffer", "Fondor"));
        recipes.add(Arrays.asList("'Chinesisiche' Suppe", "Gemüse", "Hühnerbrühe", "Frühlingszwiebel(n)", "Sojabohnen", "Sojasauce", "Sambal Oelek", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Clafoutis' mit gebratenen Feigen und Pistazien", "Feige(n)", "Butter", "Cognac", "Ei(er)", "Honig", "Mehl", "Salz", "Milch", "Pistazien", "Butter", "Rohrzucker"));
        recipes.add(Arrays.asList("'Deftige' Semmelknödel", "Brötchen", "Zwiebel(n)", "Kasseler", "Milch", "Majoran", "Muskat", "Salz und Pfeffer", "Petersilie"));
        recipes.add(Arrays.asList("'Der' Fleischsalat", "Fleischwurst", "Cornichons", "Eigelb", "Öl", "Senf", "Joghurt", "Zitronenschale", "Zitronensaft", "Salz und Pfeffer", "Paprikapulver", "Kräuter"));
        recipes.add(Arrays.asList("'Der' Kartoffelsalat", "Kartoffel(n)", "Zwiebel(n)", "Gewürzgurke(n)", "Mayonnaise", "Essig", "Salz und Pfeffer", "Zucker", "Ei(er)", "Petersilie"));
        recipes.add(Arrays.asList("'Die drei Geschmäcker'", "Mehl", "Trockenhefe", "Wasser", "Salz", "Knoblauchgranulat", "Öl"));
        recipes.add(Arrays.asList("'Die Köstlichkeit'", "Hähnchenbrustfilet(s)", "Salz und Pfeffer", "Mozzarella", "Basilikum"));
        recipes.add(Arrays.asList("'Die' Brownies", "Butter", "Zucker", "Zucker", "Schokolade", "Zuckerrübensirup", "Ei(er)", "Mehl", "Kakaopulver", "Backpulver"));
        recipes.add(Arrays.asList("'Dunja' Schnitten", "Eiweiß", "Zucker", "Semmelbrösel", "Backpulver", "Haselnüsse"));
        recipes.add(Arrays.asList("'Edle' Matjesfladen", "Matjesfilet(s)", "Mehl"));
        recipes.add(Arrays.asList("'Ei guckt durch Loch'", "Toastbrot", "Ei(er)", "Wurst", "Käse", "Gemüse", "Salz und Pfeffer", "Paprikapulver"));
        recipes.add(Arrays.asList("'Eingedeutschte' Hells Temptation", "Schokolade", "Schokolade", "Butter", "Ei(er)", "Zucker", "Zucker", "Vanillezucker", "Butter-Vanille-Aroma", "Mehl", "Kakaopulver", "Kakaopulver", "Backpulver", "Natron", "Salz", "Sauerrahm"));
        recipes.add(Arrays.asList("'Elsässer' Bratwürstchen-Sauerkrautpfanne", "Bratwürste", "Sauerkraut", "Zwiebel(n)", "Frischkäse", "Fett", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'English' - Irish Stew", "Rindfleisch", "Zwiebel(n)", "Möhre(n)", "Staudensellerie", "Kartoffel(n)", "Petersilie", "Rinderbrühe", "Salz"));
        recipes.add(Arrays.asList("'Epikuräer' - Butter", "Butter", "Sardellen", "Eigelb", "Gurke(n)", "Senf", "Estragon", "Schnittlauch"));
        recipes.add(Arrays.asList("'Falscher Hase' - Badischer Hackbraten", "Hackfleisch", "Brötchen", "Zwiebel(n)", "Salz und Pfeffer", "Senf", "Zitronenschale", "Margarine", "Bratensauce", "Sahne", "Ei(er)"));
        recipes.add(Arrays.asList("'Falscher' Flammkuchen mit Yufka - Teig", "Teig", "Crème fraîche", "Münsterkäse", "Speck", "Zwiebel(n)", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Famose Tomate'", "Tomate(n)", "Knoblauchzehe(n)", "Basilikum", "Oliven", "Tomatenmark", "Olivenöl", "Graubrot", "Salz und Pfeffer", "Zitronensaft"));
        recipes.add(Arrays.asList("'Fluffige' Blaubeermuffins", "Mehl", "Haferflocken", "Backpulver", "Natron", "Ei(er)", "Zucker", "Vanillezucker", "Butter", "saure Sahne", "Naturjoghurt", "Heidelbeeren"));
        recipes.add(Arrays.asList("'Gebackene' Schokopralinen", "Schokolade", "Butter", "Ei(er)", "Zucker", "Kuvertüre", "Butter"));
        recipes.add(Arrays.asList("'Gedinschdede' Makkaroni", "Zwiebel(n)", "Paprikapulver", "Paprikapulver", "Wasser", "Kartoffel(n)", "Nudeln", "Fleischbrühe", "Gemüsebrühe", "Margarine", "Würste"));
        recipes.add(Arrays.asList("'Gehackte Molly'  - geschichteter Eiersalat", "Remoulade", "Ei(er)", "Schinken", "Schnittlauch", "Zwiebel(n)", "Gewürzgurke(n)", "Chilipulver"));
        recipes.add(Arrays.asList("'Gehackte Stippe'", "Hackfleisch", "Zwiebel(n)", "Margarine", "Mehl", "Gemüsebrühe", "Tomatenketchup", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Geistreiches' Himbeergelee mit Stevia", "Himbeeren", "Gelierzucker", "Zitronensaft", "Vanilleschote(n)", "Himbeergeist"));
        recipes.add(Arrays.asList("'Gepimpte' Carbonara", "Spaghetti", "Ei(er)", "Speck", "Sahne", "Parmesan", "Minze", "Erbsen", "Pfeffer", "Salz"));
        recipes.add(Arrays.asList("'Gescheppte' Mehlklöße", "Brötchen", "Milch", "Ei(er)", "Salz", "Mehl"));
        recipes.add(Arrays.asList("'Gib-mir-die-Kugel' Torte", "Butter", "Zucker", "Vanillinzucker", "Ei(er)", "Haselnüsse", "Backpulver", "Konfekt", "Sahne", "Sahnesteif", "Vollmilchkuvertüre"));
        recipes.add(Arrays.asList("'Glühgold' Apfelglühwein - Grundrezept und mehr ...", "Cidre", "Apfelsaft", "Zitronensaft", "Gewürznelke(n)", "Zimt", "Apfel", "Calvados", "Sternanis", "Zucker"));
        recipes.add(Arrays.asList("'Goldene' Himbeer-Muffins vegan", "Weizenmehl", "Maismehl", "Rohrzucker", "Himbeeren", "Sojadrink", "Natron", "Backpulver", "Apfelessig", "Vanillearoma", "Zitrone(n)", "Salz", "Öl"));
        recipes.add(Arrays.asList("'Gratinierter' Obstsalat", "Banane(n)", "Orange(n)", "Apfel", "Weintrauben", "Honigmelone(n)", "Mango(s)", "Kiwi(s)", "Limettensaft", "Zucker", "Basilikum", "Schlagsahne", "Puderzucker", "Sahnequark", "Amaretto", "Keks(e)", "Krokant"));
        recipes.add(Arrays.asList("'Gratinierter' Obstsalat mit  Amaretto", "Sahne", "Quark", "Puderzucker", "Amaretto", "Limette(n)", "Basilikum", "Honigmelone(n)", "Apfel", "Birne(n)", "Banane(n)", "Nektarine(n)", "Zucker", "Krokant", "Keks(e)"));
        recipes.add(Arrays.asList("'Griechischer' Käsekuchen", "Mehl", "Butter", "Zucker", "Ei(er)", "Backpulver", "Aroma", "Salz", "Käse", "Mascarpone", "Joghurt", "Vanillezucker", "Puddingpulver", "Milch", "Sauerkirschen", "Fett"));
        recipes.add(Arrays.asList("'Grüne' Kartoffelsuppe", "Kartoffel(n)", "Zwiebel(n)", "Knoblauchzehe(n)", "Wirsing", "Wurst", "Salz und Pfeffer", "Gemüsebrühe", "Olivenöl"));
        recipes.add(Arrays.asList("'Grüne' Spaghetti", "Saucenpulver", "Kochschinken", "Zwiebel(n)", "Sahne", "Pilze", "Spaghetti", "Wasser"));
        recipes.add(Arrays.asList("'Grüne' Spaghetti mit frischen Tomaten", "Spaghetti", "Olivenöl", "Petersilie", "Tomate(n)", "Salz", "Zitronensaft"));
        recipes.add(Arrays.asList("'Grünes' Omelette mit Champignons", "Schnittlauch", "Petersilie", "Zwiebel(n)", "Champignons", "Paprikapulver", "Ei(er)", "Sojasauce", "Pfeffer", "Crème fraîche", "Butter", "Sonnenblumenkerne", "Parmesan"));
        recipes.add(Arrays.asList("'Gute Nacht' Hüttenkäse", "Hüttenkäse", "Thunfisch", "Leinsamen", "Olivenöl", "Gewürz(e)"));
        recipes.add(Arrays.asList("'Hase' (Kaninchen) in Orangen - Wurzelwerksoße", "Kaninchen", "Gemüse", "Brühe", "Preiselbeeren", "Kapern", "süße Sahne", "Weißwein", "Mehl", "Lorbeerblatt", "Nelke(n)", "Thymian", "Salz und Pfeffer", "Öl", "Orange(n)"));
        recipes.add(Arrays.asList("'Hasenohren' mit Couscous", "Aubergine(n)", "Zwiebel(n)", "Hackfleisch", "Tomate(n)", "Ziegenfrischkäse", "Milch", "Zimtpulver", "Piment", "Salz und Pfeffer", "Zucker", "Pflanzenöl"));
        recipes.add(Arrays.asList("'Haushofmeister' - Butter", "Butter", "Salz", "Cayennepfeffer", "Petersilie", "Zitrone(n)"));
        recipes.add(Arrays.asList("'Heiße Oma' - heißer Kakao mit Eierlikör", "Eierlikör", "Kakao", "Schlagsahne", "Kakaopulver"));
        recipes.add(Arrays.asList("'Hendlgulasch'", "Hähnchenschenkel", "Zwiebel(n)", "Knoblauch", "Hühnerbrühe", "Cola", "Paprikapulver", "Paprikapulver", "Tomatenmark", "Salz", "Cayennepfeffer", "Butterschmalz", "Brühe"));
        recipes.add(Arrays.asList("'Herrgottbescheißerle' - Maultaschen, so wie ich sie mache", "Teig", "Hackfleisch", "Brät", "Spinat", "Speck", "Zwiebel(n)", "Petersilie", "Lauchzwiebel(n)", "Ei(er)", "Salz und Pfeffer", "Margarine", "Eiweiß"));
        recipes.add(Arrays.asList("'Hollerblü' - Kuchen", "Butter", "Puderzucker", "Mehl", "Ei(er)", "Eigelb", "Backpulver", "Milch", "Zitrone(n)", "Holunderblütendolden", "Sirup", "Margarine"));
        recipes.add(Arrays.asList("'Johannisbeerg'", "Kuvertüre", "Kuvertüre", "Cornflakes", "Gelatine", "Naturjoghurt", "Buttermilch", "Zucker", "Johannisbeeren", "Sahne", "Minze"));
        recipes.add(Arrays.asList("'Karamellisierte' Karottensuppe", "Karotte(n)", "Butter", "Salz", "Backpulver", "Saft", "Ingwer", "Kardamom"));
        recipes.add(Arrays.asList("'Karottenkäse'", "Hüttenkäse", "Karotte(n)", "Parmesan", "Basilikum", "Salz und Pfeffer", "Zitronensaft"));
        recipes.add(Arrays.asList("'Kartoffelpampe' nach Omas Rezept", "Kartoffel(n)", "Gurke(n)", "Salatgurke(n)", "Knoblauchzehe(n)", "Gehacktes", "Zwiebel(n)", "Salz und Pfeffer", "Gurkenflüssigkeit", "Brühe"));
        recipes.add(Arrays.asList("'Kartoffelspeis' (Wurstkartoffeln)", "Kartoffel(n)", "Wurst", "Zwiebel(n)", "Knoblauchzehe(n)", "Paprikapulver", "Majoran", "Kümmel", "Petersilie", "Salz und Pfeffer", "Öl"));
        recipes.add(Arrays.asList("'Käse' zum Überbacken (vegan)", "Wasser", "Agar-Agar", "Cashewnüsse", "Kräutersalz", "Gemüsebrühe", "Möhre(n)", "Zitronensaft"));
        recipes.add(Arrays.asList("'Ki-Ba' - Torte mit Kirschen und Bananen", "Zucker", "Salz", "Ei(er)", "Vanillezucker", "Haselnüsse", "Backkakao", "Backpulver"));
        recipes.add(Arrays.asList("'KiWi'-Saftbowle", "Orangensaft", "Apfelsaft", "Pfirsichsaft", "Sirup", "Sirup"));
        recipes.add(Arrays.asList("'Kullerpfirsich' in beschwipstem Tee", "Pfirsich(e)", "Pfirsichlikör", "Puderzucker", "Tee"));
        recipes.add(Arrays.asList("'Liebestrank' auf cubanische Art", "Zucker", "Curaçao", "Portwein", "Zitrone(n)", "Muskat"));
        recipes.add(Arrays.asList("'Linde Marys' Nudelauflauf mit Schinken und Pfifferlingen", "Nudeln", "Salzwasser", "Kochschinken", "Käse", "Salz und Pfeffer", "Pfifferlinge", "Tomate(n)", "Ei(er)", "Zwiebel(n)", "Milch", "Sahne"));
        recipes.add(Arrays.asList("'Linde Marys' special Erdbeerlimes", "Erdbeeren", "Wasser", "Zucker", "Zitronensaft", "Wodka", "Rum"));
        recipes.add(Arrays.asList("'Liptauer' aus gekeimten Kichererbsen", "Kichererbsen", "Butter", "Paprikaschote(n)", "Paprikaschote(n)", "Chilischote(n)", "Gurke(n)", "Cayennepfeffer", "Paprikapulver", "Kümmelpulver", "Salz", "Pfeffer", "Knoblauchzehe(n)", "Zwiebel(n)"));
        recipes.add(Arrays.asList("'low fat' Schoko Cupcakes mit leichtem Minzfrosting", "Mehl", "Backpulver", "Zucker", "Ei(er)", "Butter", "Apfelmus", "Mineralwasser", "Kakaopulver", "Milch", "Cremepulver"));
        recipes.add(Arrays.asList("'Mal gucken, was so da ist'", "Hühnerbrust", "Mandel(n)", "Kokosmilch", "Champignons", "Kirschtomate(n)", "Salz und Pfeffer", "Reis", "Salzwasser"));
        recipes.add(Arrays.asList("'Mascarpone' selbst gemacht", "Magerquark", "Sahne", "Butter"));
        recipes.add(Arrays.asList("'Matschkartoffeln' mit Sour Cream", "Kartoffel(n)", "Sour Cream", "Frühlingszwiebel(n)", "Chilisauce", "Paprikaschote(n)", "Salz"));
        recipes.add(Arrays.asList("'Mediterranes' Ofengemüse überbacken", "Zucchini", "Paprikaschote(n)", "Chinakohl", "Zwiebel(n)", "Käse", "Rapsöl", "Thymian", "Oregano", "Basilikum", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Mein' Rotkohl", "Rotkohl", "Rotwein", "Konfitüre", "Lorbeerblätter", "Koriander", "Zwiebel(n)", "Salz und Pfeffer", "Zucker", "Wasser", "Gänseschmalz"));
        recipes.add(Arrays.asList("'Mickey Mouse - Kuchen'", "Butter", "Zucker", "Vanillezucker", "Salz", "Ei(er)", "Mehl", "Haselnüsse", "Schokolade", "Backpulver", "Fett"));
        recipes.add(Arrays.asList("'Mittelalterliche' Brotfrikadellen", "Weizenmehl", "Wasser", "Hefe", "Butter", "Salz", "Zucker", "Fett"));
        recipes.add(Arrays.asList("'Mogelmarzipan' - Kuchen", "Butter", "Zucker", "Ei(er)", "saure Sahne", "Mehl", "Kakaopulver", "Natron", "Fett"));
        recipes.add(Arrays.asList("'Nackte Mäuse'", "Hackfleisch", "Schinken", "Tomate(n)", "Sahne", "Schmand", "Salz und Pfeffer", "Gewürzmischung", "Tomatenmark"));
        recipes.add(Arrays.asList("'OBEN' - Muffins", "Zucker", "Ei(er)", "Butter", "Milch", "Mehl", "Backpulver", "Vanillinzucker", "Salz", "Zimt", "Vanille", "Lebensmittelfarbe"));
        recipes.add(Arrays.asList("'Omas' Hackfleischsauce", "Hackfleisch", "Knoblauch", "Tomatenmark", "Sahne", "Brühe", "Salz und Pfeffer", "Wasser"));
        recipes.add(Arrays.asList("'Orangeneis in der Fruchthülle' a la Xainti", "Orange(n)", "Zuckerwürfel", "Milch", "Sahne", "Orangensaft", "Eigelb", "Zucker"));
        recipes.add(Arrays.asList("'Paprika in Milch'", "Paprikaschote(n)", "Crème fraîche", "Schlagsahne", "Öl", "Salz"));
        recipes.add(Arrays.asList("'Pillen' Bratkartoffeln", "Kartoffel(n)", "Zwiebel(n)", "Speck", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Pommes' - Plätzchen", "Butter", "Mehl", "Zucker", "Ei(er)", "Aroma", "Cornflakes", "Kuvertüre", "Kuvertüre"));
        recipes.add(Arrays.asList("'Püppis' Spaghettisalat", "Spaghetti", "Paprikaschote(n)", "Schafskäse", "Olivenöl", "Kräuter", "Knoblauchzehe(n)", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("'Quark' auf amerikanische Art", "Käse", "Sauerrahm", "Schnittlauch", "Frühlingszwiebel(n)", "Schnittlauch", "Milch", "Salz"));
        recipes.add(Arrays.asList("'Rahm' - Blattspinat, fettarm", "Blattspinat", "Frischkäse", "Salz und Pfeffer", "Muskat", "Knoblauch"));
        recipes.add(Arrays.asList("'Ratatouille' mit Putenstreifen", "Zwiebel(n)", "Putenbrust", "Olivenöl", "Hähnchengewürz", "Zucchini", "Champignons", "Paprikaschote(n)", "Lorbeerblätter", "Salz", "Zucker", "Sambal Oelek", "Tomatenmark", "Knoblauchzehe(n)", "Oregano"));
        recipes.add(Arrays.asList("'Rösti' der anderen Art", "Kartoffel(n)", "Salz", "Essig", "Suppengrün", "Speisestärke", "Milch", "Pfeffer", "Speck", "Öl"));
        recipes.add(Arrays.asList("'Rumfort' - Auflauf", "Blumenkohl", "Kartoffel(n)", "Hackfleisch", "Zwiebel(n)", "Champignons", "Tomate(n)", "Milch", "Butter", "Mehl", "Knoblauch", "Käse", "Salz und Pfeffer", "Muskat", "Olivenöl", "Basilikum", "Paprikapulver"));
        recipes.add(Arrays.asList("'Rundstück warm'", "Schweinebraten", "Butter", "Knollensellerie", "Karotte(n)", "Lauch", "Zwiebel(n)", "Knoblauchzehe(n)", "Brötchen", "Salz und Pfeffer", "Paprikapulver", "Senf", "Stärkemehl", "Wasser", "Rotwein", "Fleischbrühe"));
        recipes.add(Arrays.asList("'Sahne' schnell selbst gemacht", "Milch", "Johannisbrotkernmehl", "Süßstoff", "Aroma"));
        recipes.add(Arrays.asList("'Scharfes Huhn' à la Anette - in Erdnusssauce mit Mischpilzen", "Paprikaschote(n)", "Sesamöl", "Hühnerbrust", "Sauce", "Pilze", "Erdnussbutter", "Brühe", "Salz"));
        recipes.add(Arrays.asList("'Schnecken' - Saft", "Grapefruitsaft", "Ananassaft", "Pfirsichsaft", "Sirup", "Obst"));
        recipes.add(Arrays.asList("'Schnelles' Huhn mit Wermut und Fenchel", "Poularde(n)", "Wermut", "Fenchel", "Knoblauch", "Pfeffer", "Meersalz", "Crème fraîche"));
        recipes.add(Arrays.asList("'Schnittkäse' - vegan", "Wasser", "Agar-Agar", "Cashewnüsse", "Meersalz", "Zwiebelpulver", "Knoblauchpulver", "Kurkuma", "Hefeflocken", "Zitronensaft"));
        recipes.add(Arrays.asList("'Schokolade' selbst gemacht", "Kakaopulver", "Kakaobutter", "Rohrohrzucker", "Vanillezucker"));
        recipes.add(Arrays.asList("'Schwarze Versuchung' - Schokoladenkuchen", "Mehl", "Zucker", "Backpulver", "Vanillezucker", "Butter", "Schokolade", "Schokolade", "Wasser", "Crème fraîche", "Kakaopulver", "Ei(er)", "Rum"));
        recipes.add(Arrays.asList("'Sijerlänner Muangestutz'", "Karotte(n)", "Kartoffel(n)", "Zucker", "Butter", "Salz", "Pfeffer", "Muskat"));
        recipes.add(Arrays.asList("'Streukäse' aus Sesam", "Sesam", "Hefeflocken", "Meersalz", "Zwiebelpulver", "Knoblauchpulver"));
        recipes.add(Arrays.asList("'Stroganoff' flambiert", "Rinderfilet(s)", "Öl", "Salz und Pfeffer", "Weinbrand", "Champignons", "Zwiebel(n)", "Weißwein", "süße Sahne", "Saucenpulver", "Senf", "Schnittlauch", "Gewürzgurke(n)"));
        recipes.add(Arrays.asList("'Sushi'-Bratlinge", "Reis", "Hirse", "Noriblatt", "Brühe", "Ei(er)", "Mehl", "Sojasauce", "Olivenöl", "Wasser", "Paniermehl"));
        recipes.add(Arrays.asList("'Tiramisu' aus Baileysbrot, Sauerkirschen und Hüttenkäse", "Graubrot", "Baileys Irish Cream", "Schattenmorellen", "Frischkäse", "Vanillezucker", "Zimt", "Zucker"));
        recipes.add(Arrays.asList("'Überbackene' Erdbeeren", "Erdbeeren", "Marsala", "Ei(er)", "Puderzucker", "Magerquark", "Frischkäse", "Fett"));
        recipes.add(Arrays.asList("'Übermorgen - Torte' mit Creme fraiche", "Fett", "Zucker", "Ei(er)", "Mehl", "Backpulver", "Kakaopulver", "Crème fraîche", "Vanillezucker", "Kuchenglasur", "Mandelblättchen"));
        recipes.add(Arrays.asList("'Un-badisches' Schäufele mit Rotkohl und Püree", "Schweinefleisch", "Zwiebel(n)", "Gewürznelke(n)", "Brühe", "Wacholderbeere(n)", "Lorbeerblatt", "Piment", "Rotkohl", "Zimt", "Ingwerpulver", "Ingwer", "Preiselbeeren", "Kartoffel(n)", "Milch", "Muskat", "Butter", "Salz", "Wasser"));
        recipes.add(Arrays.asList("'Vähnchenhaut' - veganer Hähnchenhautersatz", "Teigblätter", "Pflanzenöl", "Gewürzmischung"));
        recipes.add(Arrays.asList("'Weinendes' Olivenhühnchen", "Huhn", "Olivenöl", "Kartoffel(n)", "Zwiebel(n)", "Weißwein", "Thymian", "Knoblauch", "Oliven", "Salz und Pfeffer", "Paprikapulver"));
        recipes.add(Arrays.asList("'Weiße Lady' Crème fraîche-Torte", "Crème fraîche", "Quark", "Kuvertüre", "Butter", "Vanillinzucker"));
        recipes.add(Arrays.asList("'White Russian' von Sarah", "Butter", "Zucker", "Vanillezucker", "Salz", "Ei(er)", "Mehl", "Backpulver", "Kakaopulver", "Likör", "Schokoladenraspel"));
        recipes.add(Arrays.asList("'Wildkräutersalat' a la Xainti", "Löwenzahn", "Olivenöl", "Zitronensaft", "Salz und Pfeffer", "Zitrone(n)", "Wasser", "Wasser", "Feta-Käse"));
        recipes.add(Arrays.asList("'Zanjabil'", "Wasser", "Ingwer"));
        recipes.add(Arrays.asList("'Zitroniger' Zitronenkuchen", "Zitrone(n)", "Ei(er)", "Zucker", "Crème fraîche", "Mehl", "Backpulver", "Butter", "Zucker"));
        recipes.add(Arrays.asList("'Zitronisu' mit Himbeeren", "Zitrone(n)", "Puderzucker", "QimiQ", "Crème fraîche", "Zucker", "Rahm", "Löffelbiskuits", "Himbeeren"));
        recipes.add(Arrays.asList("'Züri Gschnätzlets' mit Rösti", "Kalbsgeschnetzeltes", "Champignons", "Zwiebel(n)", "Knoblauchzehe(n)", "Weißwein", "Bratenfond", "Sahne", "Butter", "Kartoffel(n)", "Sonnenblumenöl", "Salz und Pfeffer, schwarzer", "Muskat"));
        recipes.add(Arrays.asList("(Blitz) - Möhrenkuchen ohne Ei", "Rohrzucker", "Öl", "Zitronensaft", "Mehl", "Rosinen", "Backpulver", "Aroma", "Möhre(n)", "Äpfel", "Obst", "Fett"));
        recipes.add(Arrays.asList("(Eier-)Schwammerlstrudel", "Pfifferlinge", "Schinkenwürfel", "Zwiebel(n)", "Ei(er)", "Salz und Pfeffer", "Petersilie", "Mehl", "Wasser, lauwarm", "Öl", "Salz", "Essig", "Butter"));
        recipes.add(Arrays.asList("(Falsche) Wurstbrühnudeln mit Fleischklößchen", "Bandnudeln", "Wasser", "Hackepeter", "Brühe", "Majoran", "Blutwurst"));
        recipes.add(Arrays.asList("(Hähnchen)Geschnetzeltes nach Gyros Art", "Hähnchenbrust", "Zwiebel(n)", "Knoblauchzehe(n)", "Gewürzmischung", "Öl"));
        recipes.add(Arrays.asList("(Iced) Chai Tea Latte wie von Starbucks", "Tee", "Milch", "Zucker", "Vanilleschote(n)", "Eiswürfel"));
        recipes.add(Arrays.asList("(K)Golatsche oder Obstküchle", "Mehl", "Zucker", "Eigelb", "Butter", "Backpulver", "Vanillinzucker", "Zitrone(n)", "Haselnüsse", "Marzipan", "Rum", "Banane(n)", "Apfel", "Pfirsich(e)", "Pflaume(n)", "Kirsche(n)", "Quark", "Eiweiß", "Zitronensaft"));
        recipes.add(Arrays.asList("(K)östlicher Reissalat", "Reis", "Lauchzwiebel(n)", "Kochschinken", "Paprikaschote(n)", "Mais", "Zitrone(n)", "Senf", "Sojasauce", "Chilisauce", "Sesamöl", "Salz und Pfeffer", "Gewürzmischung"));
        recipes.add(Arrays.asList("(Kentucky...) Fried Chicken im Südstaaten-Stil", "Hähnchen", "Buttermilch", "Sauce", "Senf", "Mehl", "Backpulver", "Glutamat", "Chilipulver", "Salz und Pfeffer", "Öl"));
        recipes.add(Arrays.asList("(N)urbrot", "Sonnenblumenkerne", "Leinsamen", "Haselnüsse", "Haferflocken", "Chiasamen", "Flohsamen", "Salz", "Ahornsirup", "Kokosöl", "Wasser"));
        recipes.add(Arrays.asList("(Safer) Sex on the Beach", "Ananassaft", "Pfirsichsaft", "Sirup", "Eis", "Ananas"));
        recipes.add(Arrays.asList("(Schlanker) Kochkäse nach Annies Rezept", "Butter", "Sahne-Schmelzkäse", "Käse", "Natron", "Sauerrahm", "Kümmel", "Pfeffer", "Kondensmilch"));
        recipes.add(Arrays.asList("(Siegerländer) Räiwekechelcher", "Kartoffel(n)", "Ei(er)", "Salz", "Haferflocken", "Öl", "Butterschmalz"));
        recipes.add(Arrays.asList("(V)Liptauer", "Quarkersatz", "Margarine", "Paprikapulver, edelsüß", "Paprikapulver, rosenscharf", "Senf, süßer", "Knoblauchzehe(n)", "Kümmelpulver", "Schalotte(n)", "Essiggurke(n)", "Kapern", "Salz und Pfeffer", "Zucker"));
        recipes.add(Arrays.asList("(Weihnachts-)Apfel-Likör", "Apfelsaft", "Wodka", "Zucker", "Vanilleschote(n)", "Gewürznelke(n)", "Gewürzmischung", "Zimt"));
        recipes.add(Arrays.asList("*Adas Polo ba khorma* Linsenreis mit Datteln und Rosinen", "Basmatireis", "Linsen", "Zwiebel(n)", "Zimt", "Kardamom", "Salz und Pfeffer", "Öl", "Rosinen", "Dattel(n)", "Mandelstifte", "Zucker", "Kartoffel(n)", "Safran"));
        recipes.add(Arrays.asList("*Besonderer* Streuselkuchen mit Johannisbeeren", "Puderzucker", "Eigelb", "Butter", "Mehl"));
        recipes.add(Arrays.asList("*Falsche* Kiwitorte", "Tortenboden", "Sahnesteif", "Quark", "Sahne", "Vanillezucker", "Zucker", "Götterspeise", "Zucker"));
        recipes.add(Arrays.asList("*Roher* Grünkernsalat", "Grünkern", "Salatgurke(n)", "Karotte(n)", "Frühlingszwiebel(n)", "Feta-Käse", "Peperoni", "Öl", "Essig", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("*Schweinenüsschenbraten*", "Schweinebraten", "Suppengrün", "Paprikaschote(n)", "Knoblauchzehe(n)", "Kräuter", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("*Shole sard* süßer Safranreis mit Rosenwasser", "Reis", "Wasser", "Safran", "Zucker", "Butter", "Rosenwasser", "Kardamom", "Zimt", "Pistazien"));
        recipes.add(Arrays.asList("*Vierkant*", "Sirup", "Wein", "Schnaps", "Rum"));
        recipes.add(Arrays.asList(",,La Tendresse''oder ,,Die Zärtlichkeit''", "Mandel(n)", "Zucker", "Ei(er)", "Butter", "Mehl", "Schokolade", "Butter", "Puderzucker"));
        recipes.add(Arrays.asList(",Die Sauce' für Currywurst, stückig", "Tomaten, stückige", "Zwiebel(n)", "Apfel", "Paprikaschote(n), rot", "Knoblauch", "Sonnenblumenöl", "Ingwerpulver", "Thai-Currypulver", "Zucker, braun", "Salz", "Balsamico, dunkler", "Paprikamark", "Honig", "Sojasauce", "Einmachhilfe"));
        recipes.add(Arrays.asList("-JeaNet-s Käsetaler", "Emmentaler", "Parmesan", "Butter", "Mehl", "Ei(er)", "Naturjoghurt", "Knoblauchzehe(n)", "Salz", "Pfeffer"));
        recipes.add(Arrays.asList("0 - Punkte - Gemüsetopf", "Weißkohl", "Kohlrabi", "Frühlingszwiebel(n)", "Zucchini", "Paprikaschote(n)", "Zwiebel(n)", "Lauch", "Rosenkohl", "Knoblauchzehe(n)", "Petersilie", "Gemüsebrühe", "Lorbeerblätter", "Korianderpulver", "Kümmelpulver", "Oregano", "Tomate(n)", "Sojasauce", "Tabasco", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("0-Punkte-Dessert  aus Bananen und Kakao", "Banane(n)", "Kakao", "Wasser", "Agavendicksaft"));
        recipes.add(Arrays.asList("007  -  Tomaten - Champignon - Soße", "Tomate(n)", "Champignons", "Gemüsebrühe", "Tomatenmark", "Salz und Pfeffer", "Chilipulver"));
        recipes.add(Arrays.asList("007 Brot", "Sauerteig", "Roggenmehl", "Weizenmehl", "Salz", "Malz", "Wasser", "Hefe"));
        recipes.add(Arrays.asList("08 / 15 - Kuchen", "Mehl", "Margarine", "Zucker", "Backpulver", "Ei(er)"));
        recipes.add(Arrays.asList("08/15 Gugelhupf", "Ei(er)", "Butter", "Puderzucker", "Milch", "Mehl", "Backpulver", "Rosinen", "Milch", "Butter"));
        recipes.add(Arrays.asList("08/15 Kartoffelbrot", "Sauerteig", "Kartoffel(n)", "Roggenvollkornmehl", "Weizenmehl", "Salz", "Wasser", "Hefe", "Brotgewürzmischung"));
        recipes.add(Arrays.asList("1 - 2 - 3 - 4 - 5 - Cake", "Vanillezucker", "Backpulver", "Butter", "Zucker", "Mehl", "Ei(er)"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Bananen-Krokant-Kuchen", "Biskuitboden", "Vanillepuddingpulver", "Zucker", "Milch", "Banane(n)", "Zitronensaft", "Schlagsahne"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Biskuit", "Ei(er)", "Zucker", "Mehl"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Frosting", "Butter", "Puderzucker", "Milch"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Joghurtbecherkuchen", "Joghurt", "Mehl", "Backpulver", "Zucker", "Ei(er)", "Öl", "Vanillezucker", "Mandel(n)", "Zucker", "Butter"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Nudeln mit Schinken und Rosmarin", "Nudeln", "Salzwasser", "Schinken", "Olivenöl", "Rosmarin", "Zitronenschale", "Chili", "Salz und Pfeffer", "Parmesan"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Nudeln: Rosa Prinzessinnensauce", "Nudeln", "Ziegenfrischkäse", "Tomatenmark", "Salz und Pfeffer", "Ketchup", "Parmesan"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Spritzgebäck", "Mehl", "Butter", "Puderzucker"));
        recipes.add(Arrays.asList("1 - 2 - 3 - Suppe mit Ei", "Fleischbrühe", "Nudeln", "Ei(er)", "Parmesan", "Petersilie", "Worcestersauce"));
        recipes.add(Arrays.asList("1 - 2 - 3 Butter - Plätzchen", "Butter", "Vanillezucker", "Zucker", "Ei(er)", "Mehl", "Speisestärke"));
        recipes.add(Arrays.asList("1 - 2 - 3 Buttercreme", "Eiweiß", "Zucker", "Butter", "Aroma"));
        recipes.add(Arrays.asList("1 - 2 - 3 Salatdressing", "Rotweinessig", "Senf", "Honig", "Olivenöl", "Salz und Pfeffer", "Schnittlauch"));
        recipes.add(Arrays.asList("1 - 2 - 3 Zwiebeln", "Wasser", "Salz", "Zucker", "Essigessenz", "Zwiebel(n)"));
        recipes.add(Arrays.asList("1 - 2 - Fertig - Tassenkuchen mit Obst", "Mehl", "Zucker", "Mineralwasser", "Öl", "Ei(er)", "Backpulver", "Vanillezucker", "Obst", "Puderzucker"));
        recipes.add(Arrays.asList("1 - A - Kräuterbutter", "Butter", "Kräuter", "Knoblauchzehe(n)", "Zitronensaft", "Salz"));
        recipes.add(Arrays.asList("1 2 3 Kekse", "Zucker", "Butter", "Mehl", "Ei(er)"));
        recipes.add(Arrays.asList("1 a - Kirsch - Joghurtkuchen mit Choco Crossies", "Butter", "Mehl", "Backpulver", "Zucker", "Vanillezucker", "Ei(er)", "Milch"));
        recipes.add(Arrays.asList("1 A Apfel-Eierpfannkuchen", "Mehl", "Zucker", "Ei(er)", "Milch", "Mineralwasser", "Backpulver", "Äpfel"));
        recipes.add(Arrays.asList("1 A Bratapfelkuchen mit Pudding", "Butter", "Zucker", "Ei(er)", "Mehl", "Backpulver"));
        recipes.add(Arrays.asList("1 A Eierpfannkuchen", "Mehl", "Zucker", "Ei(er)", "Milch", "Mineralwasser", "Backpulver", "Pflanzenöl"));
        recipes.add(Arrays.asList("1 A falscher Eierlikör", "Kondensmilch", "Schnaps"));
        recipes.add(Arrays.asList("1 A gebackene Garnelen", "Garnele(n)", "Kräuterbutter", "Salz und Pfeffer"));
        recipes.add(Arrays.asList("1 A Gratiniertes mit Nudeln, Hack und Spinat", "Nudeln", "Hackfleisch", "Zwiebel(n)", "Knoblauch", "Blattspinat", "Frühlingszwiebel(n)", "Gemüsebrühe", "Schafskäse", "Wasser"));
        recipes.add(Arrays.asList("1 A Hackfleisch - Schnecken", "Pizzateig", "Zwiebel(n)", "Knoblauchzehe(n)", "Salz und Pfeffer", "Öl", "Hackfleisch", "Käse"));
        recipes.add(Arrays.asList("1 A Kaffee - Creme - Likör", "Kondensmilch", "Schnaps", "Kaffeepulver"));
        recipes.add(Arrays.asList("1 A Knoblauchgewürz", "Knoblauchzehe(n)", "Salz"));
        recipes.add(Arrays.asList("1 A Lemongrassalz", "Salz", "Öl"));
        recipes.add(Arrays.asList("1 A Marzipan - Rum Schneckenkuchen", "Hefe", "Milch", "Wasser", "Margarine", "Zucker", "Ei(er)", "Salz", "Weizenmehl"));
        recipes.add(Arrays.asList("1 A Mint - After - Eight - Schoko - Likör", "Kondensmilch", "Schnaps", "Kakaopulver"));
        recipes.add(Arrays.asList("1 a Nudeln mit Schinken - Sahne - Sauce", "Nudeln", "Sahne", "Kochschinken", "Margarine", "Mehl", "Milch", "Brühe"));
        recipes.add(Arrays.asList("1 A Omelette mediterran", "Tomate(n)", "Zwiebel(n)", "Peperoni", "Oliven", "Ei(er)", "Salz und Pfeffer", "Paprikapulver", "Knoblauch", "Olivenöl", "Wasser", "Parmesan", "Mozzarella"));
        recipes.add(Arrays.asList("1 A Orangenzucker", "Zucker", "Aroma"));
        recipes.add(Arrays.asList("1 A Salzmandeln", "Mandel(n)", "Butterschmalz", "Salz"));
        recipes.add(Arrays.asList("1 A Schlammbowle à la Tina", "Mandarine(n)", "Wodka", "Orangensaft", "Sekt", "Eis"));
        recipes.add(Arrays.asList("1 A Suppengewürz", "Möhre(n)", "Sellerie", "Porree", "Zwiebel(n)", "Petersilie", "Schnittlauch", "Schnittknoblauch", "Knoblauch", "Kräuter", "Salz"));
        recipes.add(Arrays.asList("1 A Vanillezucker", "Zucker", "Aroma"));
        recipes.add(Arrays.asList("1 A Waffelrezept", "Mehl", "Zucker", "Vanillezucker", "Butter", "Ei(er)", "Milch", "Backpulver", "Rum"));
        recipes.add(Arrays.asList("1 A Zitronenzucker", "Zucker", "Aroma"));
        recipes.add(Arrays.asList("1 A Zucchini - Hackfleisch - Pfanne", "Hackfleisch", "Zucchini", "Pilze", "Zwiebel(n)", "Sahne", "Salz", "Pfeffer", "Brühe", "Paprikapulver"));
        recipes.add(Arrays.asList("1 kg Fleischgericht", "Rindfleisch", "Schweinefleisch", "Kasseler", "Mett", "Tomate(n)", "Zwiebel(n)", "Knoblauchzehe(n)", "Chilisauce", "süße Sahne"));
        recipes.add(Arrays.asList("1 Kg Unkeler - Bierbrot", "Mehl", "Mehl", "Bier", "Hefe", "Salz"));
        recipes.add(Arrays.asList("1 Minute Sour Creme", "Crème fraîche", "Kräuterquark", "Salz und Pfeffer", "Kräuter"));
        recipes.add(Arrays.asList("1 Minute Tomatensauce", "Tomate(n)", "Knoblauchzehe(n)", "Tomatenmark", "Zwiebel(n)", "Olivenöl", "Salz und Pfeffer", "Thymian", "Oregano", "Rosmarin", "Basilikum"));
        recipes.add(Arrays.asList("1 Pott Ofenpfanne", "Gehacktes", "Zucchini", "Karotte(n)", "Lauch", "Zwiebel(n)", "Knoblauch", "Gemüsebrühe", "Reis", "Salz und Pfeffer", "Paprika", "Kräuter", "Öl", "Käse"));
        recipes.add(Arrays.asList("1 Teig - 5 Sorten Plätzchen", "Butter", "Mehl", "Zucker", "Salz", "Ei(er)", "Haselnüsse", "Mandel(n)", "Vanillinzucker", "Zimt", "Nutella", "Walnusskerne", "Himbeerkonfitüre", "Puderzucker", "Eigelb", "Bitterschokolade", "Aprikosenkonfitüre"));
        recipes.add(Arrays.asList("1 Vater - 2 Söhne - Pasta", "Nudeln", "Hackfleisch", "Tomate(n)", "Sardellen", "Kapern", "Zwiebel(n)", "Knoblauch", "Oregano", "Salz und Pfeffer", "Olivenöl"));
        recipes.add(Arrays.asList("1, 2, 3 Kirschmichel", "Sojamilch (Sojadrink)", "Toastbrot", "Kirsche(n)"));
        recipes.add(Arrays.asList("1, 2, 3 Vitamindrink", "Orange(n)", "Kiwi(s)", "Himbeeren", "Apfelsaft", "Honig", "Mineralwasser"));
        recipes.add(Arrays.asList("1-2-3 - Obstkuchen mit Crème fraiche", "Zucker", "Butter", "Mehl", "Ei(er)"));
        recipes.add(Arrays.asList("1-2-3 - Salat", "Salatgurke(n)", "Kohlrabi", "Kräuter", "Salz und Pfeffer", "Essig"));
    }
}